//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class arenda
    {
        public int Arenda_Id { get; set; }
        public Nullable<int> Arendator_Id { get; set; }
        public string Nazvanie_TC { get; set; }
        public Nullable<int> Sotrudnil_Id { get; set; }
        public string Pavilion { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> nachalo_Arend { get; set; }
        public Nullable<System.DateTime> konec_Arend { get; set; }
    
        public virtual Arendator Arendator { get; set; }
        public virtual Sotrudniki Sotrudniki { get; set; }
        public virtual TC1 TC1 { get; set; }
    }
}
