//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class pavilion
    {
        public int ID { get; set; }
        public string nazvanie_Tc { get; set; }
        public string nomer_paviliona { get; set; }
        public Nullable<int> etaj { get; set; }
        public string status { get; set; }
        public Nullable<double> plochad { get; set; }
        public Nullable<double> stoimost_za_kv { get; set; }
        public Nullable<double> kof_dobav_stoimosti { get; set; }
    
        public virtual TC1 TC1 { get; set; }
    }
}
