//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class TC1
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TC1()
        {
            this.arenda = new HashSet<arenda>();
            this.pavilion = new HashSet<pavilion>();
        }
    
        public int id { get; set; }
        public string Nazvanie { get; set; }
        public string Status { get; set; }
        public Nullable<int> Kol_Pavilionov { get; set; }
        public string Gorod { get; set; }
        public Nullable<double> Stoimost { get; set; }
        public Nullable<double> Kof_Dobav_Stoimosti { get; set; }
        public Nullable<int> Etajnost { get; set; }
        public byte[] Fhoto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<arenda> arenda { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pavilion> pavilion { get; set; }
    }
}
